# .travis.yml
language: node_js

node_js:
  - '4'
  - '6'
  - '7'

before_install:
  - sudo apt-get install -y unicode-data

install:
  - npm install

before_script:
  - npm run-script dev-build

notifications:
  email: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

matrix:
  fast_finish: true
